//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Expenses = new HashSet<Expens>();
            this.Products = new HashSet<Product>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public string Vendor_Name { get; set; }
        public Nullable<int> ExpenseID { get; set; }
    
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
